/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ActivateRouteImport } from './routes/activate'
import { Route as ActivateStaffRouteImport } from './routes/activate-staff'
import { Route as ActivateTeacherRouteImport } from './routes/activate-teacher'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AdminsRouteImport } from './routes/admins'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as LoginRouteImport } from './routes/login'
import { Route as StaffRouteImport } from './routes/staff'
import { Route as StaffAccountsRouteImport } from './routes/staff-accounts'
import { Route as TeacherRouteImport } from './routes/teacher'
import { Route as TeachersRouteImport } from './routes/teachers'
import { Route as UnauthorizedRouteImport } from './routes/unauthorized'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivateRoute = ActivateRouteImport.update({
  id: '/activate',
  path: '/activate',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivateStaffRoute = ActivateStaffRouteImport.update({
  id: '/activate-staff',
  path: '/activate-staff',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivateTeacherRoute = ActivateTeacherRouteImport.update({
  id: '/activate-teacher',
  path: '/activate-teacher',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminsRoute = AdminsRouteImport.update({
  id: '/admins',
  path: '/admins',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffRoute = StaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffAccountsRoute = StaffAccountsRouteImport.update({
  id: '/staff-accounts',
  path: '/staff-accounts',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherRoute = TeacherRouteImport.update({
  id: '/teacher',
  path: '/teacher',
  getParentRoute: () => rootRouteImport,
} as any)
const TeachersRoute = TeachersRouteImport.update({
  id: '/teachers',
  path: '/teachers',
  getParentRoute: () => rootRouteImport,
} as any)
const UnauthorizedRoute = UnauthorizedRouteImport.update({
  id: '/unauthorized',
  path: '/unauthorized',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/activate': typeof ActivateRoute
  '/activate-staff': typeof ActivateStaffRoute
  '/activate-teacher': typeof ActivateTeacherRoute
  '/admin': typeof AdminRoute
  '/admins': typeof AdminsRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/staff': typeof StaffRoute
  '/staff-accounts': typeof StaffAccountsRoute
  '/teacher': typeof TeacherRoute
  '/teachers': typeof TeachersRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/activate': typeof ActivateRoute
  '/activate-staff': typeof ActivateStaffRoute
  '/activate-teacher': typeof ActivateTeacherRoute
  '/admin': typeof AdminRoute
  '/admins': typeof AdminsRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/staff': typeof StaffRoute
  '/staff-accounts': typeof StaffAccountsRoute
  '/teacher': typeof TeacherRoute
  '/teachers': typeof TeachersRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/activate': typeof ActivateRoute
  '/activate-staff': typeof ActivateStaffRoute
  '/activate-teacher': typeof ActivateTeacherRoute
  '/admin': typeof AdminRoute
  '/admins': typeof AdminsRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/staff': typeof StaffRoute
  '/staff-accounts': typeof StaffAccountsRoute
  '/teacher': typeof TeacherRoute
  '/teachers': typeof TeachersRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/activate'
    | '/activate-staff'
    | '/activate-teacher'
    | '/admin'
    | '/admins'
    | '/dashboard'
    | '/login'
    | '/staff'
    | '/staff-accounts'
    | '/teacher'
    | '/teachers'
    | '/unauthorized'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/activate'
    | '/activate-staff'
    | '/activate-teacher'
    | '/admin'
    | '/admins'
    | '/dashboard'
    | '/login'
    | '/staff'
    | '/staff-accounts'
    | '/teacher'
    | '/teachers'
    | '/unauthorized'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/activate'
    | '/activate-staff'
    | '/activate-teacher'
    | '/admin'
    | '/admins'
    | '/dashboard'
    | '/login'
    | '/staff'
    | '/staff-accounts'
    | '/teacher'
    | '/teachers'
    | '/unauthorized'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActivateRoute: typeof ActivateRoute
  ActivateStaffRoute: typeof ActivateStaffRoute
  ActivateTeacherRoute: typeof ActivateTeacherRoute
  AdminRoute: typeof AdminRoute
  AdminsRoute: typeof AdminsRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  StaffRoute: typeof StaffRoute
  StaffAccountsRoute: typeof StaffAccountsRoute
  TeacherRoute: typeof TeacherRoute
  TeachersRoute: typeof TeachersRoute
  UnauthorizedRoute: typeof UnauthorizedRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activate': {
      id: '/activate'
      path: '/activate'
      fullPath: '/activate'
      preLoaderRoute: typeof ActivateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activate-staff': {
      id: '/activate-staff'
      path: '/activate-staff'
      fullPath: '/activate-staff'
      preLoaderRoute: typeof ActivateStaffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activate-teacher': {
      id: '/activate-teacher'
      path: '/activate-teacher'
      fullPath: '/activate-teacher'
      preLoaderRoute: typeof ActivateTeacherRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admins': {
      id: '/admins'
      path: '/admins'
      fullPath: '/admins'
      preLoaderRoute: typeof AdminsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff': {
      id: '/staff'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof StaffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff-accounts': {
      id: '/staff-accounts'
      path: '/staff-accounts'
      fullPath: '/staff-accounts'
      preLoaderRoute: typeof StaffAccountsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher': {
      id: '/teacher'
      path: '/teacher'
      fullPath: '/teacher'
      preLoaderRoute: typeof TeacherRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teachers': {
      id: '/teachers'
      path: '/teachers'
      fullPath: '/teachers'
      preLoaderRoute: typeof TeachersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/unauthorized': {
      id: '/unauthorized'
      path: '/unauthorized'
      fullPath: '/unauthorized'
      preLoaderRoute: typeof UnauthorizedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActivateRoute: ActivateRoute,
  ActivateStaffRoute: ActivateStaffRoute,
  ActivateTeacherRoute: ActivateTeacherRoute,
  AdminRoute: AdminRoute,
  AdminsRoute: AdminsRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  StaffRoute: StaffRoute,
  StaffAccountsRoute: StaffAccountsRoute,
  TeacherRoute: TeacherRoute,
  TeachersRoute: TeachersRoute,
  UnauthorizedRoute: UnauthorizedRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
